### ISSUE TITLE
Can you update for iOS 13 ?

### ISSUE THREAD

**Issue by Potterd** [tomaszpoliszuk/MagSafeEnabler#2]

**Comment by DevLiuSir** [comment]
The author mentioned, This package is compatible with iOS iOS 12.0 to 14.0.1.

**Comment by Potterd** [comment]
Package description states that this tweak is valid for iOS 14.1 and above.  I did not see any entry where the developer states that the tweak is compatible with iOS 12 to 14.0.1.  Attempt to install using Cydia wiht iOS 13.5 generates errors.  Attempt to execute after install with errors, and the tweak doesn't work.

Conclusion: tweak is compatible with iOS 14.1 and higher as stated.  My original message was a request to the developer to consider updating for iOS 13.

**Comment by DevLiuSir** [comment]
> Package description states that this tweak is valid for iOS 14.1 and above. I did not see any entry where the developer states that the tweak is compatible with iOS 12 to 14.0.1. Attempt to install using Cydia wiht iOS 13.5 generates errors. Attempt to execute after install with errors, and the tweak doesn't work.
> 
> Conclusion: tweak is compatible with iOS 14.1 and higher as stated. My original message was a request to the developer to consider updating for iOS 13.

I did not pay attention to your description, but I added the author source to cydia. 1.0.2 has been used.

**Comment by Potterd** [comment]
Can you please provide the location of the updated v1.0.2 - Thank you !

**Comment by DevLiuSir** [comment]
> Can you please provide the location of the updated v1.0.2 - Thank you !

Source: https://MTAC.app/beta/

**Comment by Potterd** [comment]
Thanks !

However, this appears to be a different developer than the github version.

David Potter
DPotter Consulting Inc
(415) 485-5876 (office)
(415) 608-7797 (mobile)
David@dpotterconsulting.com

You can view me on LinkedIn: www.linkedin.com/in/dpotterconsulting

**Comment by tomaszpoliszuk** [comment]
I've released https://github.com/tomaszpoliszuk/MagSafeController - it's currently compatible with 13+ - you can download it from BigBoss repo - this one will stay iOS 14.1+ only.

Have a nice day!
